In [6]:
import matplotlib.pyplot as plt

In [12]:
import pandas as pd

In [13]:
caminho_municipios = r"C:\Projetos\LearningDataAnalysis\dados\atlasMunicipios.csv"

In [14]:
caminho_dados = r"C:\Projetos\LearningDataAnalysis\dados\mediaEnemPorMunicipio.csv"

In [22]:
municipios = pd.read_csv(caminho_municipios, sep=",", encoding='utf-8')

In [23]:
municipios = municipios[municipios['ANO'] == 2010] #ESCOLHENDO O ANO DE ANALISE

In [24]:
dadosEnem = pd.read_csv(caminho_dados, sep=",", index_col=0, encoding='utf-8')

In [25]:
enem_municipios = pd.merge(dadosEnem, municipios, how='left', left_on=['CO_MUNICIPIO_ESC'], right_on=['Codmun7'])

In [26]:
mediaEnemIDHM = enem_municipios.filter(['CO_MUNICIPIO_ESC','NO_MUNICIPIO_ESC', 'SG_UF_ESC',
                                  'CO_UF_ESC', 'NU_NOTA_MT', 'NU_NOTA_LC',
                                  'NU_NOTA_CH', 'NU_NOTA_CN', 'NU_NOTA_REDACAO',
                                  'IDHM', 'IDHM_E', 'IDHM_L', 'IDHM_R'])
mediaEnemIDHM

,CO_MUNICIPIO_ESC,NO_MUNICIPIO_ESC,SG_UF_ESC,CO_UF_ESC,NU_NOTA_MT,NU_NOTA_LC,NU_NOTA_CH,NU_NOTA_CN,NU_NOTA_REDACAO,IDHM,IDHM_E,IDHM_L,IDHM_R
0,1100015.0,Alta Floresta D'Oeste,RO,11.0,502.991429,495.929730,543.020270,480.664286,453.783784,0.641,0.526,0.763,0.657
1,1100023.0,Ariquemes,RO,11.0,512.975890,513.304727,549.247267,481.314239,461.418021,0.702,0.600,0.806,0.716
2,1100031.0,Cabixi,RO,11.0,484.925000,466.007407,506.685185,442.604167,391.111111,0.650,0.559,0.757,0.650
3,1100049.0,Cacoal,RO,11.0,524.946720,513.924809,549.739357,484.990720,482.419602,0.718,0.620,0.821,0.727
4,1100056.0,Cerejeiras,RO,11.0,493.949296,498.394737,551.494737,466.433803,440.789474,0.692,0.602,0.799,0.688
...,...,...,...,...,...,...,...,...,...,...,...,...,...
5553,5222005.0,Vianópolis,GO,52.0,503.091765,493.386517,522.414607,474.571765,446.516854,0.712,0.622,0.818,0.710
5554,5222054.0,Vicentinópolis,GO,52.0,479.803226,463.625641,498.125641,439.651613,362.051282,0.684,0.562,0.804,0.707
5555,5222203.0,Vila Boa,GO,52.0,504.900000,450.394444,513.100000,440.164286,346.666667,0.647,0.534,0.818,0.619
5556,5222302.0,Vila Propício,GO,52.0,471.051667,463.396825,498.101587,451.296667,369.206349,0.634,0.505,0.802,0.629
5557,5300108.0,Brasília,DF,53.0,552.578598,546.609685,580.567979,510.176935,546.970747,0.824,0.742,0.873,0.863

In [18]:
enem_municipios.columns.values

<StringArray>
['CO_MUNICIPIO_ESC', 'NO_MUNICIPIO_ESC',        'SG_UF_ESC',
        'CO_UF_ESC',       'NU_NOTA_MT',       'NU_NOTA_LC',
       'NU_NOTA_CH',       'NU_NOTA_CN',  'NU_NOTA_REDACAO',
               'UF',
 ...
          'PIA1517',           'PIA18M',              'POP',
             'POPT',   'I_ESCOLARIDADE',      'I_FREQ_PROP',
             'IDHM',           'IDHM_E',           'IDHM_L',
           'IDHM_R']
Length: 248, dtype: str

In [19]:
municipios.head()

,UF,Codmun6,Codmun7,Município,LONG,LAT,Alt,ESPVIDA,FECTOT,MORT1,...,PIA1517,PIA18M,POP,POPT,I_ESCOLARIDADE,I_FREQ_PROP,IDHM,IDHM_E,IDHM_L,IDHM_R
ANO,,,,,,,,,,,,,,,,,,,,,
1991,RONDÔNIA,110001,1100015,ALTA FLORESTA D'OESTE,-61.999824,-11.935540,337.735719,62.01,4.08,45.58,...,NaN,NaN,23417,22835,0.117,0.109,0.329,0.112,0.617,0.516
1991,RONDÔNIA,110002,1100023,ARIQUEMES,-63.033269,-9.908463,138.688981,66.02,3.72,32.39,...,NaN,NaN,56061,55018,0.200,0.199,0.432,0.199,0.684,0.593
1991,RONDÔNIA,110003,1100031,CABIXI,-60.544314,-13.499763,236.063160,63.16,3.89,41.52,...,NaN,NaN,7601,5846,0.111,0.106,0.309,0.108,0.636,0.430
1991,RONDÔNIA,110004,1100049,CACOAL,-61.442944,-11.433865,177.453547,65.03,3.81,35.37,...,NaN,NaN,69173,66534,0.176,0.169,0.407,0.171,0.667,0.593
1991,RONDÔNIA,110005,1100056,CEREJEIRAS,-60.818426,-13.195033,262.811307,62.73,3.55,43.00,...,NaN,NaN,19451,19030,0.152,0.175,0.386,0.167,0.629,0.547